[options]
addons_path = /mnt/extra-addons
admin_passwd = admin123
db_host = aws-1-ap-southeast-1.pooler.supabase.com
db_port = 5432
db_user = postgres.dejvjdrdjqdgmughoyle
db_password = Anish123!
db_name = postgres
log_level = info

